//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacLuong
    {
        public string MaBL { get; set; }
        public string MaCV { get; set; }
        public Nullable<int> MucLuongBac_I { get; set; }
        public Nullable<int> MucLuongBac_II { get; set; }
        public Nullable<int> MucLuongBac_III { get; set; }
        public Nullable<int> MucLuongBac_IV { get; set; }
        public Nullable<int> MucLuongBac_V { get; set; }
        public Nullable<int> MucLuongBac_VI { get; set; }
        public Nullable<int> MucLuongBac_VII { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
    }
}
