//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongLaoDong
    {
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public string MaLoaiHD { get; set; }
        public Nullable<System.DateTime> NgayBDHD { get; set; }
        public Nullable<System.DateTime> NgayKTHD { get; set; }
    
        public virtual LoaiHopDong LoaiHopDong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
