//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRManagerEntities5 : DbContext
    {
        public HRManagerEntities5()
            : base("name=HRManagerEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChamCong> ChamCongs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<HopDongLaoDong> HopDongLaoDongs { get; set; }
        public virtual DbSet<LoaiHopDong> LoaiHopDongs { get; set; }
        public virtual DbSet<LoaiKLKT> LoaiKLKTs { get; set; }
        public virtual DbSet<LoaiNghiPhep> LoaiNghiPheps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuCongTac> PhieuCongTacs { get; set; }
        public virtual DbSet<PhieuDieuChuyen> PhieuDieuChuyens { get; set; }
        public virtual DbSet<PhieuKLKT> PhieuKLKTs { get; set; }
        public virtual DbSet<PhieuLuong> PhieuLuongs { get; set; }
        public virtual DbSet<PhieuNghiPhep> PhieuNghiPheps { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<BacLuong> BacLuongs { get; set; }
        public virtual DbSet<NgayNghiCoDinh> NgayNghiCoDinhs { get; set; }
    
        public virtual int prUpdateChuyenPB(string maPBden, string maNV)
        {
            var maPBdenParameter = maPBden != null ?
                new ObjectParameter("MaPBden", maPBden) :
                new ObjectParameter("MaPBden", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prUpdateChuyenPB", maPBdenParameter, maNVParameter);
        }
    
        public virtual int prUpdateSoGioLamViec(string maCC)
        {
            var maCCParameter = maCC != null ?
                new ObjectParameter("MaCC", maCC) :
                new ObjectParameter("MaCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prUpdateSoGioLamViec", maCCParameter);
        }
    
        public virtual int prThemNgayNghi(string soPhieuNP, string maNV, string maLoaiNP, Nullable<System.DateTime> ngayBDNghi, Nullable<System.DateTime> ngayDiLam, string anhNghiPhepNV, string noiDungNP, ObjectParameter ngayNghiConLai)
        {
            var soPhieuNPParameter = soPhieuNP != null ?
                new ObjectParameter("SoPhieuNP", soPhieuNP) :
                new ObjectParameter("SoPhieuNP", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maLoaiNPParameter = maLoaiNP != null ?
                new ObjectParameter("MaLoaiNP", maLoaiNP) :
                new ObjectParameter("MaLoaiNP", typeof(string));
    
            var ngayBDNghiParameter = ngayBDNghi.HasValue ?
                new ObjectParameter("NgayBDNghi", ngayBDNghi) :
                new ObjectParameter("NgayBDNghi", typeof(System.DateTime));
    
            var ngayDiLamParameter = ngayDiLam.HasValue ?
                new ObjectParameter("NgayDiLam", ngayDiLam) :
                new ObjectParameter("NgayDiLam", typeof(System.DateTime));
    
            var anhNghiPhepNVParameter = anhNghiPhepNV != null ?
                new ObjectParameter("AnhNghiPhepNV", anhNghiPhepNV) :
                new ObjectParameter("AnhNghiPhepNV", typeof(string));
    
            var noiDungNPParameter = noiDungNP != null ?
                new ObjectParameter("NoiDungNP", noiDungNP) :
                new ObjectParameter("NoiDungNP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prThemNgayNghi", soPhieuNPParameter, maNVParameter, maLoaiNPParameter, ngayBDNghiParameter, ngayDiLamParameter, anhNghiPhepNVParameter, noiDungNPParameter, ngayNghiConLai);
        }
    
        public virtual int prUpdateSoNgayNPConLai(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prUpdateSoNgayNPConLai", maNVParameter);
        }
    }
}
