//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HRManagerEntities6 : DbContext
    {
        public HRManagerEntities6()
            : base("name=HRManagerEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChamCong> ChamCongs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<HopDongLaoDong> HopDongLaoDongs { get; set; }
        public virtual DbSet<LoaiHopDong> LoaiHopDongs { get; set; }
        public virtual DbSet<LoaiKLKT> LoaiKLKTs { get; set; }
        public virtual DbSet<LoaiNghiPhep> LoaiNghiPheps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuCongTac> PhieuCongTacs { get; set; }
        public virtual DbSet<PhieuDieuChuyen> PhieuDieuChuyens { get; set; }
        public virtual DbSet<PhieuKLKT> PhieuKLKTs { get; set; }
        public virtual DbSet<PhieuLuong> PhieuLuongs { get; set; }
        public virtual DbSet<PhieuNghiPhep> PhieuNghiPheps { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<BacLuong> BacLuongs { get; set; }
    
        public virtual int prUpdateChuyenPB(string maPBden, string maNV)
        {
            var maPBdenParameter = maPBden != null ?
                new ObjectParameter("MaPBden", maPBden) :
                new ObjectParameter("MaPBden", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prUpdateChuyenPB", maPBdenParameter, maNVParameter);
        }
    
        public virtual int prUpdateSoGioLamViec(string maCC)
        {
            var maCCParameter = maCC != null ?
                new ObjectParameter("MaCC", maCC) :
                new ObjectParameter("MaCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prUpdateSoGioLamViec", maCCParameter);
        }
    }
}
