//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgayNghiCoDinh
    {
        public string MaNN { get; set; }
        public string TenNN { get; set; }
        public Nullable<System.DateTime> NgayNghi { get; set; }
    }
}
