//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChamCongs = new HashSet<ChamCong>();
            this.HopDongLaoDongs = new HashSet<HopDongLaoDong>();
            this.PhieuCongTacs = new HashSet<PhieuCongTac>();
            this.PhieuDieuChuyens = new HashSet<PhieuDieuChuyen>();
            this.PhieuKLKTs = new HashSet<PhieuKLKT>();
            this.PhieuLuongs = new HashSet<PhieuLuong>();
            this.PhieuNghiPheps = new HashSet<PhieuNghiPhep>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public string MaNV { get; set; }
        public string MaCV { get; set; }
        public string MaPB { get; set; }
        public string CCCD { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        public string QueQuan { get; set; }
        public string NoiOHienTai { get; set; }
        public string DienThoai { get; set; }
        public string TrinhDoHocVan { get; set; }
        public Nullable<int> SoNgayNPConLai { get; set; }
        public string AnhDaiDienNV { get; set; }
        public string Email { get; set; }
        public bool TinhTrangTaiKhoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamCong> ChamCongs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongLaoDong> HopDongLaoDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuCongTac> PhieuCongTacs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDieuChuyen> PhieuDieuChuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuKLKT> PhieuKLKTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuLuong> PhieuLuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNghiPhep> PhieuNghiPheps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
